### ISSUE TITLE
Page header settings

### ISSUE THREAD

**Issue by skydogtech** [maithemewp/mai-starter#1]
In the Page Header settings, will there be a way to move the banner content to the left, middle, or right side of the banner area? I can still do text alignment there in v2, but def. need to be able to control where the header goes in relation to its background image.

**Comment by JiveDig** [comment]
You can still do that now, but the settings are slightly different:

<img width="736" alt="Screen Shot 2020-04-30 at 12 59 59" src="https://user-images.githubusercontent.com/540990/80738164-8feae780-8ae2-11ea-9942-344b8c726082.png">

**Comment by skydogtech** [comment]
Yeah, in that case, it's not actually working.. it is aligning the header text itself, but it stays in the center of the banner area.

**Comment by JiveDig** [comment]
Interesting. So you want the content alignment setting where the main inner container gets aligned independently of the text inside it. So we can do like our Law demo has...

<img width="1445" alt="Screen Shot on 2020-04-30 at 13-31-59" src="https://user-images.githubusercontent.com/540990/80741041-038ef380-8ae7-11ea-8e23-e52abb9a0c58.png">

**Comment by skydogtech** [comment]
yes! exactly! That's almost always what my banners look like
